Hw03 mongodb
VitaliiVeshtobei/nodejs-homework-rest-api pull request #2
Opened 2022-12-30 16:39 UTC by VitaliiVeshtobei

Привіт, зробив 3 дз. Перевір будь ласка!

2022-12-30 19:59 UTC, KhYulian commented on middlewares/middlewareContacts.js
> +    res.status(404).json({ message: "Not found" });
Зазвичай пишуть навпаки :)
 if (!contact) { 
return res.status(404)... 
}
 res.status(200)...

2022-12-30 19:59 UTC, KhYulian commented on middlewares/middlewareContacts.js
> +    res.status(404).json({ message: "Not found" });
Аналогічно в інших місцях

2022-12-30 20:00 UTC, KhYulian commented on middlewares/middlewareContacts.js
> +    console.log(error.message);
Помилки потрібно обробляти. В кетч викликай next і передавай туди error

2022-12-30 20:00 UTC, KhYulian commented on middlewares/middlewareContacts.js
> +    console.log(error.message);
аналогічно в інших місцях

2022-12-30 20:00 UTC, KhYulian requested changes
Потрібне доопрацювання

2022-12-30 20:48 UTC, VitaliiVeshtobei commented on middlewares/middlewareContacts.js
> +    res.status(404).json({ message: "Not found" });
Зробив, але побачив що коли воджу невірний id. то чтомусь мені у відповідь приходить пустий масив... Нібито цей If(!contactById) не спрацьовує

2022-12-30 20:48 UTC, VitaliiVeshtobei commented on middlewares/middlewareContacts.js
> +    console.log(error.message);
Зробив...

2022-12-31 09:02 UTC, KhYulian commented on middlewares/middlewareContacts.js
> +    res.status(404).json({ message: "Not found" });
Коли робите запит на один елемент масив ніколи не має повертатись. Використовуйте метод findOne || findById

2022-12-31 09:03 UTC, KhYulian commented
І не забувайте подавати роботу в лмс. Бо на пошту я отримую багато поівдомлень і можу пропустити повідомлення про ваші допрацювання

2022-12-31 09:10 UTC, KhYulian commented on middlewares/middlewareContacts.js
> +    res.status(404).json({ message: "Not found" });
інші методи можуть повертати трохи інший результат (remove - deleted count) - перевірте, що повертають ці мотоди та відповідно відкорегуйте перевірки

2022-12-31 10:04 UTC, VitaliiVeshtobei commented on middlewares/middlewareContacts.js
> +    res.status(404).json({ message: "Not found" });
Я трохи переплутав... в postman повертало пустий обʼєкт и статус 500, я так розумію це від mongo db вже йшло. але пофіксив , зараз працює.

2022-12-31 10:36 UTC, KhYulian approved these changes
Чудова робота 😎

2022-12-31 10:36 UTC, merged